// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjrgvPngoEv4AfD-Gf4d86PJxsjpYpWDI',
    appId: '1:975657109570:web:f7512061702dfe690545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    authDomain: 'eventium-74c4c.firebaseapp.com',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
    measurementId: 'G-9F78ZDGZKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCje7EUV8OF80bFfxECVsz4L8G27pghuR8',
    appId: '1:975657109570:android:39accbe36d49d8fa0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_-pquObe541kx9fZnzDXeEv-J-Bo6Krg',
    appId: '1:975657109570:ios:70316cc4c07b888f0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
    iosBundleId: 'com.example.eventPlannerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_-pquObe541kx9fZnzDXeEv-J-Bo6Krg',
    appId: '1:975657109570:ios:70316cc4c07b888f0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
    iosBundleId: 'com.example.eventPlannerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjrgvPngoEv4AfD-Gf4d86PJxsjpYpWDI',
    appId: '1:975657109570:web:bd5ef148ad2d65fc0545db',
    messagingSenderId: '975657109570',
    projectId: 'eventium-74c4c',
    authDomain: 'eventium-74c4c.firebaseapp.com',
    storageBucket: 'eventium-74c4c.firebasestorage.app',
    measurementId: 'G-P9D00VJCNZ',
  );
}
